workflows:
  android-debug:
    name: Android Debug
    instance_type: mac_mini_m1
    environment:
      groups:
        - android
    scripts:
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
